### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'Dimension'

### ISSUE THREAD

**Issue by chaotianjiao** [a312863063/seeprettyface-generator-wanghong#6]
你好~       运行genrate_wanghong.py的时候报了这个错：
AttributeError: module 'tensorflow' has no attribute 'Dimension'
我使用的是tensorflow-gpu 2.0.0 ,不知道应该怎么改，大神可以教教我吗~百度了半天也查不到，谢谢了

**Comment by sole12343** [comment]
你的tensorflow版本是2.0以上的，这些模块只有1.0的那些才有，卸载重装吧（老子就不写英文）
